services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-x370
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_DATABASE: jukeboxd_db
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
